server {
    listen 80;
    root /usr/share/nginx/html;

    # Serve pages as index
    location = / {
        rewrite ^/$ /pages/index.html break;
    }

    # Handle page requests
    location / {
        # Try as file, then as directory with index.html, then in pages directory
        try_files $uri $uri/ /pages$uri /pages$uri/index.html =404;
    }

    # Serve static assets (wp-core, includes, assets, etc)
    location ~* ^/(wp-core|includes|assets|feed|comments|robots.txt)/ {
        try_files $uri =404;
    }
}

